/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    ATable: typeof import('ant-design-vue/es')['Table']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ZGTable: typeof import('./src/components/ZGTable.vue')['default']
  }
}
